language: generic

cache:
  directories:
    - /tmp/awx-rpmbuild-cache

addons:
  artifacts:
    s3_region: eu-west-1
    debug: true
    branch: master
    paths:
      - $(ls result/*.x86_64.rpm | tr "\n" ":")

env:
  global:
    - secure: QxHEA6JI3Vv6mIoKtJ0Ppcfv2jJPyIpndUc9sUOHp5rfslMONxps09PL2d0iTtGikXnWKuHRr14F/geia1WvRgCYokbaNDAtd9iHpkWit1OTRL9cipF5KxQA4WNEp9FyatOZ5qCkyWRFzG3TX2NdgtFgYXFW6puC2Zvr6Su1EIwzzonf4Ne9VHFFYTSV3SqqslVsBxm9skXMDxWb6zWAZKZrTL9qNZ/9LzO+k/qw1mtYLP52GqVPloyOr1EBgmIFbd+eIC0hd6ODGdTcqfOvL2sP2aQlEPLpOX6Sc8fbXmbOKosYrwM/NEJX1/oy2Fz60BpqFqrdeBMo1GHu2rIiJ2+7lutnhsynD5C94QhaLkTLyP3Dx6v+G+9jXrmFgaxaxY3EhtP/GE6K0TdgnJsQB8fiXzH2iTYVvOfZzUvhPY2XEFc0hQpo/yX5L+XK6MhykyFJmAEtw0hp3tMKkEgip38+qRaLd6mNDfvcXTfFDM37WtwLC7zF50nhK12YzTqOtgbJfaBV05rqvCi0lIXZ7C1MNxewYcnGGB638hGPipvf7CX3rMp7N3DdLQQRfZgzaFbIsGld0npr19xVs8r6W6Jg9OP4GNfLBAzCT68HgKtDVPPnNfShX7QW9HCiZ23yBsxcLfGzopKwVotgD6L14Lpn7bJAwXBpNLKXKki9xuI=
    - secure: bBtCr0GWFBj4yeHGD5ti3DrJus4M8idcxHNJH8VH07yDv4oP4JAeGsINn1pj/39meWpMgDDzJvr1cj3KCLGzCk1Gijr5vAc4ahx6y84Qc4wry2g7OoerQp/zv8NWzrny6CWg547o2vHwAhoLWIeiQbHr4qeL+J/e0AoVf1qOY0pQSj6Mch6dK9Er0G5bR9vsowVsiY+/+N6TpyuDQXllUrEgV0fbIBh57UpnxmfqceXYajVfPMuoQb5dQXv0c3T7NvF0R5lmL0VceT9jFhZAMvHl+5732jILw9PDwNkZdwKYfS/UFGerZLxJoW3f/qYZQ0iTQcaM7ie5KM4MwmmwsdRTnhLSuB/x2acVrLYCiFdRoAPrGkOWJT3FlbloURr07ipmtTIJ+A4wJEjbaRH3JhcalCPGqcqOW/6VSgh/R3Mljs9V/mXmh2M6QwgiDz4Oz1M7OLnz/768XLQ8Re+QB0JIfAmpdr02yZUaSVh4c2R1gSD/3sSlrOP+sFQ1eiDqL33mfyUhD0WOOonQBx9eqEG2nrLIkyaTEyQDZkBqjaK/9XCc98N1rVcUZ2JcaSZbBZfQtGqNFNBzvLxZwLMVN8PgBO4MlgS3mFMbFJWueUc5gRfE5Yzg54VPTQb8To/s5qjD/zatg668Y07C2B8PrKO0hBCo7vN70xt7NNFs9UM=
    - secure: m3sf6PD8Y388rs6cfh6ZvnhjfdCOy7jb1Rm8g4CEM7qtfsSh14AEdcADiw0jfaGih+aHyFVW6kuRgzDpqYgz/0SppTuLimP0ByIrzp6Vv6nEE5i1BTRyN5zzJBW6IV1rM+B3J5qCCfOMpSxS+lVq9IgqQkT8e5UCNThBFHKOxf0AbmyjJ/IOtDOiVQSPrbGUiNndFjJbNoytsuQbTNUnnTdQjlHIjnUZ0UxLwYdSq9LuqW+fZK/G3l4IsiozikE1U9BGaRe9I6U2hAsny2xePkY9w40tsGdMKpEt+UBSprv7jobAWkrmObTz++f60NtjNTC4jJdRrkE3AuDDyv/NbbXve+TswQMTpyqidpQA/F216CCrH80pxERvzQTsbuD6dgi055lt3pmNzXroHU7aXsH0jZxOWNQZKANFwklxMo/OkkF/u5aTDDyWar+INExfTkVxN4tZ5x9GpipgSfeaWt6NnDMP10MygvTysMc64jkekr/+jGdSkWT70mF/i0dSLQj6nnkbpYnfZ+F3Ml7fhOZqYynIMfwX2d9U/pFRiL4NjPBvoeVo567MsWzJzoBQh/SXHrXLEl1gKAPV3XrqWbxCc5DXLmlKJUcH+2fdAnaqupvT9U6DWvyhJ6a3Ef7jXkP2yis0tegE45MF15cIvwPA2uYHwbJWWSHjpWPJFps=
services:
  - docker

matrix:
  include:
    - env: BUILD_DISTRO=amazonlinux-2017.03
    - env: BUILD_DISTRO=centos-7

script:
  - ./build.sh ${BUILD_DISTRO}
